from typing import List, Protocol
from app.domain.models.post import Post


class PostRepository(Protocol):
    def save(self, post: Post) -> Post: ...
    def get_all(self) -> List[Post]: ...
    def get_by_id(self, post_id: int) -> Post | None: ...
